export const Nosotros = {
  id: "nosotros",
  theme: "lightBg",
  heading: "headingLight",
  text: "textLight",
  rows: "InfoRow2",
  topLine: "Nuestra Historia",
  headline: "Nosotros",
  description: "Viaja por los 9 niveles de Mictlán y vive la experiencia de nuestros ancestros en la mejor comida y deliciosas bebidas.",
  buttonLabel: "Descubre más",
  linkBtn:"",
  imgStart: true,
  img: "/images/vato.jpg",
  alt: "otro",
  dark: true,
  primary: true,
  darkText: true,
  dark2: false,
}

export const Reservaciones = {
  id: "reservaciones",
  theme: "lightBg",
  heading: "headingLight",
  text: "textLight",
  rows: "InfoRow1",
  topLine: "Reservaciones",
  headline: "Asegura tu lugar",
  description: "Xolotl, el dios guía, ayuda a las almas a pasar por los peligros y obstáculos en su travesía por Mictlán, el inframundo..",
  buttonLabel: "Reserva ahora mismo",
  wha: true,
  linkBtn:"https://wa.me/8129397423",
  imgStart: false,
  img: "/images/reservation.webp",
  alt: "otro",
  dark: true,
  dark2: false,
  primary: true,
  darkText: true
}
