import { FaWhatsapp } from "react-icons/fa"

export const Nosotros = {
  id: "nosotros",
  theme: "lightBg",
  heading: "headingLight",
  text: "textLight",
  rows: "InfoRow2",
  topLine: "Nuestra Filosofía",
  headline: "Nosotros",
  description: "En el corazón de nuestro Restaurante-Bar Mictlán late una filosofía inspirada en la profunda leyenda azteca del Mictlán.",
  description2: "Buscamos ofrecer una experiencia trascendental a través de sabores y sensaciones que reflejan la dualidad de la vida y la muerte. Fusionamos lo tradicional y lo contemporáneo, celebrando la diversidad y honrando la herencia cultural.",
  description3: "Nuestro objetivo es mantener viva la esencia de nuestra tradición y compartir nuestra riqueza histórica con los comensales. Viaja por los 9 niveles de Mictlán y vive la experiencia de nuestros ancestros en la mejor comida y deliciosas bebidas.",
  buttonLabel: "Descubre más",
  linkBtn:"",
  imgStart: true,
  img: "/images/vato.jpg",
  alt: "otro",
  dark: true,
  primary: true,
  darkText: true,
  dark2: false,
}

export const Reservaciones = {
  id: "reservaciones",
  theme: "lightBg",
  heading: "headingLight",
  text: "textLight",
  rows: "InfoRow1",
  topLine: "Reservaciones",
  headline: "Asegura tu lugar",
  description: "Xolotl, el dios guía, ayuda a las almas a pasar por los peligros y obstáculos en su travesía por Mictlán, el inframundo..",
  description2: "Contactanos dando CLICK en el icono de whatsapp y asegura tu lugar en nuestro Restaurante-Bar Mictlán9.",
  buttonLabel: "Reserva ahora mismo",
  wha: true,
  linkBtn:"https://wa.me/8111832550",
  imgStart: false,
  img: "/images/reservation.webp",
  alt: "otro",
  dark: true,
  dark2: false,
  primary: true,
  darkText: true
}
